package com.event.customTypes;

/**
 * EVENTID_TEXT 事件编号 CERTAINTY_TEXT 确定性程度 DEATH_NUM 死亡人数 DIRECTLOSS_NUM 直接损失
 * ECONOMICLOCSS_NUM 经济损失总量 INDIRECTLOSS_NUM 非直接损失 INHERITANCE_TEXT 继承关系描述
 * INJURE_NUM 受伤人员损失 MISSING_NUM 失踪人数 MOHUQUERY_TEXT 模糊查询 PATTERN_TEXT 模式查询
 * SEVERITY_TEXT 严重程度 URGENCY_TEXT 紧急程度 BBOX_POLYGON 空间范围 EVENTTIME_DATE 事件发生时间
 * 
 * @author yxliang
 * 
 */

public enum EventOperationTypes {
	EVENTID_TEXT_ONE_CONTAIN, CERTAINTY_TEXT_ONE_CONTAIN, DEATH_NUM_TWO_BETWEEN, DIRECTLOSS_NUM_TWO_BETWEEN, ECONOMICLOCSS_NUM_TWO_BETWEEN, INDIRECTLOSS_NUM_TWO_BETWEEN, INHERITANCE_TEXT_ONE_CONTAIN, INJURE_NUM_TWO_BETWEEN, MISSING_NUM_TWO_BETWEEN, MOHUQUERY_TEXT_ONE_CONTAIN, PATTERN_TEXT_ONE_CONTAIN, SEVERITY_TEXT_ONE_CONTAIN, URGENCY_TEXT_ONE_CONTAIN, BBOX_POLYGON_ONE_BECONTAIN, EVENTTIME_DATE_TWO_BETWEEN
}
