package com.model.customTypes;
/**
 * 进行的一系列的model查询组合操作
 * @author yxliang
 *
 */
public enum ModelOperationTypes {
	MODEL_ID_TEXT_ONE_CONTAIN,
	MODEL_APPLICATION_TEXT_ONE_CONTAIN,
	MODEL_FUNCTION_TEXT_ONE_CONTAIN,
	MODEL_KEYWORDS_TEXT_ONE_CONTAIN,
	MODEL_LONGNAME_TEXT_ONE_CONTAIN,
	MODEL_PERSONNAME_TEXT_ONE_CONTAIN,
	MODEL_SHORTNAME_TEXT_ONE_CONTAIN,
	MODEL_WORKSPACE_TEXT_ONE_CONTAIN
}
